name: Deploy ECS

on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        description: 'The image tag to deploy'
        type: string
      environment:
        required: true
        description: 'The environment to deploy to (e.g., testing, production)'
        type: string

jobs:
  deploy-ecs:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fill in the new image ID in the task definition
      run: |
        sed -e "s|<IMAGE_URI>|${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ inputs.image_tag }}|g" \
            .infra/${{inputs.environment}}-task-definition.json > computed-task-definition.json
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        aws-region: eu-central-1
        
    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: computed-task-definition.json
        service: ${{inputs.environment}}-service
        cluster: ${{inputs.environment}}-cluster
        wait-for-service-stability: true
      env:
        AWS_REGION: eu-central-1