name: CI Pull Request
  
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: install dotnet format
      run: dotnet tool install -g dotnet-format

    - name: Build
      run: dotnet build --no-restore

    - name: Unit tests
      run: dotnet test --no-build --verbosity normal

    - name: Check code format
      run: dotnet format --verify-no-changes