name: CI/CD Main Branch

on:
  push:
    branches: [ main ]

jobs:
  call-build-test-module:
    uses: ./.github/workflows/1-build-test-module.yml
  
  call-create-release-module:
    uses: ./.github/workflows/2-create-release-module.yml
    needs: call-build-test-module
    secrets: inherit

  call-deploy-testing-ecs-module:
    uses: ./.github/workflows/3-deploy-ecs-module.yml
    needs: call-create-release-module
    secrets: inherit
    with:
      image_tag: ${{ needs.call-create-release-module.outputs.image_tag }}
      environment: testing
  
  call-deploy-production-ecs-module:
    uses: ./.github/workflows/3-deploy-ecs-workflow.yml
    needs: call-create-release-module
    secrets: inherit
    with:
      image_tag: ${{ needs.call-create-release-module.outputs.image_tag }}
      environment: production