name: CI/CD Main Branch

on:
  push:
    branches: [ main ]

jobs:
  call-build-test-workflow:
    uses: ./.github/workflows/1-build-test-workflow.yml
  
  call-create-release-worfkflow:
    uses: ./.github/workflows/2-create-release-workflow.yml
    needs: call-build-test-workflow
    secrets: inherit

  call-deploy-testing-ecs-workflow:
    uses: ./.github/workflows/3-deploy-ecs-workflow.yml
    needs: call-create-release-worfkflow
    secrets: inherit
    with:
      image_tag: ${{ needs.call-create-release-worfkflow.outputs.image_tag }}
      environment: testing
  
  call-deploy-production-ecs-workflow:
    uses: ./.github/workflows/3-deploy-ecs-workflow.yml
    needs: call-create-release-worfkflow
    secrets: inherit
    with:
      image_tag: ${{ needs.call-create-release-worfkflow.outputs.image_tag }}
      environment: production